<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdc71b9627c0dc4f312c6f98a532d8ea6
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Predis\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Predis\\' => 
        array (
            0 => __DIR__ . '/..' . '/predis/predis/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Sentinel' => 
            array (
                0 => __DIR__ . '/..' . '/jamescauwelier/psredis/lib',
            ),
        ),
        'P' => 
        array (
            'PSRedis' => 
            array (
                0 => __DIR__ . '/..' . '/jamescauwelier/psredis/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdc71b9627c0dc4f312c6f98a532d8ea6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdc71b9627c0dc4f312c6f98a532d8ea6::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitdc71b9627c0dc4f312c6f98a532d8ea6::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
